apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: audiobookserver
  namespace: utils
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: audiobookserver
    spec:
      containers:
      - name: audiobookserver
        image: lowet84/audiobookserver
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/out/Data"
          name: volume
          subPath: Settings/audiobookserver
        - mountPath: "/data/"
          name: volume
          subPath: Audiobooks
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: utils-claim
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookserver
  namespace: utils
spec:
  ports:
  - port: 5000
  selector:
    app: audiobookserver
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: audiobookserver
  namespace: utils
spec:
  rules:
  - host: audiobookserver.local
    http:
      paths:
      - backend:
          serviceName: audiobookserver
          servicePort: 5000
