apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guacamole
  namespace: utils
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: glyptodon/guacamole
        ports:
        - containerPort: 8080
        env:
        - name: GUACD_HOSTNAME
          value: "guacd"
        - name: GUACD_PORT
          value: "4822"
        - name: MYSQL_DATABASE
          value: "guacamole_db"
        - name: MYSQL_HOSTNAME
          value: "guacamole-mysql.utils.svc.cluster.local"
        - name: MYSQL_PASSWORD
          value: "guacamole_password"
        - name: MYSQL_USER
          value: "guacamole_user"
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: "/etc/nginx/"
          name: nginx-config
      volumes:
      - name: nginx-config
        configMap:
          name: guacamole-nginx-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guacd
  namespace: utils
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacd
        image: glyptodon/guacd
        ports:
        - containerPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: utils
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30808
    name: guacamole
  - port: 8081
    name: nginx
  selector:
    app: guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: utils
spec:
  ports:
  - port: 4822
  selector:
    app: guacd
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guacamole
  namespace: utils
spec:
  rules:
  - host: guacamole.local
    http:
      paths:
      - backend:
          serviceName: guacamole
          servicePort: 8081
---
apiVersion: v1
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8081;
        location / {
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   Host      $http_host;
            proxy_pass         http://guacamole:8080/guacamole/;
        }
      }
    }
kind: ConfigMap
metadata:
#  creationTimestamp: 2017-03-06T14:40:34Z
  name: guacamole-nginx-config
  namespace: utils
#  resourceVersion: "474849"
#  selfLink: /api/v1/namespaces/utils/configmaps/guacamole-nginx
#  uid: daeb0cd4-027a-11e7-bccd-8c89a5c49d66
---

