apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: samba
  namespace: utils
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        args: 
#        - -u "fredrik;gurkburk" 
        - -s 
        - "public;/data"
        image: dperson/samba
        ports:
        - containerPort: 137
        - containerPort: 138
        - containerPort: 139
        - containerPort: 445
        volumeMounts:
        - mountPath: "/data"
          name: utils-volume
      volumes:
      - name: utils-volume
        persistentVolumeClaim:
          claimName: utils-claim
---
apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: utils
spec:
  type: NodePort
  ports:
  - port: 137
    nodePort: 30137
    name: "137"
  - port: 138
    nodePort: 30138
    name: "138"
  - port: 139
    nodePort: 30139
    name: "139"
  - port: 445
    nodePort: 30445
    name: "445"
  selector:
    app: samba
