apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
  namespace: mediaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - name: deluge
        image: linuxserver/deluge
        ports:
        - containerPort: 8112
        - containerPort: 58846
        volumeMounts:
        - mountPath: "/config"
          name: deluge-volume
          subPath: Settings/deluge
#        - mountPath: "/data/TV"
#          name: deluge-volume
#          subPath: TV
        - mountPath: "/data/Film"
          name: deluge-volume
          subPath: Film
        - mountPath: "/data/Downloads"
          name: deluge-volume
          subPath: Downloads
#        - mountPath: "/data/TVCharlotte"
#          name: deluge-volume
#          subPath: TVCharlotte
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "SE"
      volumes:
      - name: deluge-volume
        persistentVolumeClaim:
          claimName: mediaserver-claim
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: mediaserver
spec:
  ports:
  - port: 8112
    name: "web"
  - port: 58846
    name: "daemon"
  selector:
    app: deluge
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge
  namespace: mediaserver
spec:
  rules:
  - host: deluge.local
    http:
      paths:
      - backend:
          serviceName: deluge
          servicePort: 8112
