apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
  namespace: mediaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - name: sabnzbd
        image: lsioarmhf/deluge
        ports:
        - containerPort: 8112
        volumeMounts:
        - mountPath: "/config"
          name: mfs-volume
          subPath: deluge
        - mountPath: "/downloads"
          name: mfs-volume
          subPath: data
        - mountPath: "/incomplete-downloads"
          name: mfs-volume
          subPath: incomplete-data
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      volumes:
      - name: mfs-volume
        persistentVolumeClaim:
          claimName: mediaserver-claim
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: mediaserver
spec:
  ports:
  - port: 8112
  selector:
    app: deluge
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge
  namespace: mediaserver
spec:
  rules:
  - host: deluge.cluster
    http:
      paths:
      - backend:
          serviceName: deluge
          servicePort: 8112
