apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plex
  namespace: mediaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: lsioarmhf/plex
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: "/config"
          name: mfs-volume
          subPath: plex
        - mountPath: "/downloads"
          name: mfs-volume
          subPath: data
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      volumes:
      - name: mfs-volume
        persistentVolumeClaim:
          claimName: mediaserver-claim
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: mediaserver
spec:
  type: NodePort
  ports:
    - port: 32400
      nodePort: 32400
      name: plex
  selector:
    app: plex
