apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plex
  namespace: mediaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: lsioarmhf/plex:latest
#       livenessProbe:
#         httpGet:
#           path: /
#           port: 32400
#         initialDelaySeconds: 60
#         timeoutSeconds: 15
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: "/config"
          name: mfs-volume
          subPath: plex
        - mountPath: "/data"
          name: mfs-volume
          subPath: data
        env:
        - name: VERSION
          value: "latest"
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      volumes:
      - name: mfs-volume
        persistentVolumeClaim:
          claimName: mediaserver-claim
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: plex
#  namespace: mediaserver
#spec:
#  ports:
#    - port: 32400
#  selector:
#    app: plex
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: plex
#  namespace: mediaserver
#spec:
#  rules:
#  - host: plex.cluster
#    http:
#      paths:
#      - backend:
#          serviceName: plex
#          servicePort: 32400
