apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: mediaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lsioarmhf/sabnzbd
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/config"
          name: sabnzbd-volume
          subPath: sabnzbd
        - mountPath: "/downloads"
          name: sabnzbd-volume
          subPath: data
        - mountPath: "/incomplete-downloads"
          name: sabnzbd-volume
          subPath: incomplete-data
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      volumes:
      - name: sabnzbd-volume
        persistentVolumeClaim:
          claimName: mediaserver-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: mediaserver
spec:
  ports:
  - port: 8080
  selector:
    app: sabnzbd
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: mediaserver
spec:
  rules:
  - host: sabnzbd.cluster
    http:
      paths:
      - backend:
          serviceName: sabnzbd
          servicePort: 8080
