apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: sameersbn/postgresql:9.6-2
        ports:
        - containerPort: 5432
        env:
        - name: DB_NAME
          value: "gitlabhq_production"
        - name: DB_USER
          value: "gitlab" 
        - name: DB_PASS
          value: "password"
        - name: DB_EXTENSION
          value: "pg_trgm"
        volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: ci-volume
          subPath: gitlab/postgres
      volumes:
      - name: ci-volume
        persistentVolumeClaim:
          claimName: ci-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: ci
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: sameersbn/redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/var/lib/redis"
          name: ci-volume
          subPath: gitlab/redis
      volumes:
      - name: ci-volume
        persistentVolumeClaim:
          claimName: ci-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redisio
  namespace: ci
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:8.16.6
        ports:
        - containerPort: 22
          name: "ssh"
        - containerPort: 80
          name: "web"
        env:
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: "dflijfsdp92j23cl4jli324jcli32jc4ij32"
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: "309c4l830948c209348l02394c098l09284c"
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: "z03d8c47b3w98759n798n75987n985985qwe"
        - name: DB_PASS
          value: "password"
        - name: DB_USER
          value: "gitlab"
        volumeMounts:
        - mountPath: "/home/git/data"
          name: ci-volume
          subPath: gitlab/gitlab
      volumes:
      - name: ci-volume
        persistentVolumeClaim:
          claimName: ci-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: ci
spec:
  ports:
  - port: 80
  selector:
    app: gitlab
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: ci
spec:
  rules:
  - host: gitlab.kube
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: 80
