apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-srv
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-srv
    spec:
      containers:
      - name: registry-srv
        image: registry
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/lib/registry/"
          name: ci-volume
          subPath: registry
      volumes:
      - name: ci-volume
        persistentVolumeClaim:
          claimName: ci-claim
---
apiVersion: v1
kind: Service
metadata:
  name: registry-srv
  namespace: ci
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30005
  selector:
    app: registry-srv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-web
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-web
    spec:
      containers:
      - name: registry-web
        image: hyper/docker-registry-web
        ports:
        - containerPort: 8080
        env:
        - name: REGISTRY_URL
          value: "http://registry-srv:5000/v2"
        - name: REGISTRY_NAME
          value: "registry-srv:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-web
  namespace: ci
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30008
  selector:
    app: registry-web
