apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/lib/registry/"
          name: ci-volume
          subPath: registry
        env:
        - name: SEARCH_BACKEND
          value: "sqlalchemy"
      volumes:
      - name: ci-volume
        persistentVolumeClaim:
          claimName: ci-claim
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: ci
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30005
  selector:
    app: registry
