#apiVersion: v1
#kind: Namespace
#metadata:
#  name: lizardfs
#---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: lizardfs-master
  namespace: lizardfs
spec:
  template:
    metadata:
      labels:
        app: lizardfs-master
    spec:
      containers:
      - name: lizardfs-master
        image: lowet84/lizardfs-master
        ports:
        - containerPort: 9419
        - containerPort: 9420
        - containerPort: 9421
        volumeMounts:
        - mountPath: /var/lib/mfs
          name: lizardfs-volume
      volumes:
      - name: lizardfs-volume
        hostPath:
          path: /var/lib/lizardfs
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: lizardfs-chunk
  namespace: lizardfs
spec:
  template:
    metadata:
      labels:
        app: lizardfs-chunk
    spec:
      containers:
      - name: lizardfs-chunk
        image: lowet84/lizardfs-chunk
        ports:
        - containerPort: 9422
        volumeMounts:
        - mountPath: /mnt
          name: lizardfs-data-volume
        env:
        - name: MFSMASTER
          value: lizardfs-master.lizardfs.svc.cluster.local
      volumes:
      - name: lizardfs-data-volume
        hostPath:
          path: /lizardfs-data
      nodeSelector:
        lizardfs: storage
---
apiVersion: v1
kind: Service
metadata:
  name: lizardfs-master
  namespace: lizardfs
spec:
  type: NodePort
  ports:
  - port: 9421
    nodePort: 30421
    name: "9421"
  - port: 9420
    name: "9420"
  - port: 9419
    name: "9419"
  selector:
    app: lizardfs-master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lizardfs-cgi
  namespace: lizardfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lizardfs-cgi
    spec:
      containers:
      - name: sonarr
        image: lowet84/lizardfs-cgi
        ports:
        - containerPort: 9425
---
apiVersion: v1
kind: Service
metadata:
  name: lizardfs-cgi
  namespace: lizardfs
spec:
  ports:
  - port: 9425
  selector:
    app: lizardfs-cgi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lizardfs-cgi
  namespace: lizardfs
spec:
  rules:
  - host: lizardfs.kube
    http:
      paths:
      - backend:
          serviceName: lizardfs-cgi
          servicePort: 9425
