kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/filer/Volumes"
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-volume2
  labels:
    type: local
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/filer/Volumes"
  persistentVolumeReclaimPolicy: Retain
