kind: PersistentVolume
apiVersion: v1
metadata:
  name: mfs-volume
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mfs/"
  persistentVolumeReclaimPolicy: Recycle
